import React from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useLibrary } from '../../context/LibraryContext';
import { useToast } from '../../context/ToastContext';
import { MemberForm } from '../../components/library/MemberForm';
import { Button } from '../../components/ui/Button';
import { ArrowLeft } from 'lucide-react';
import { MemberStatus } from '../../types';

export const MemberCreatePage: React.FC = () => {
  const { members, addMember, getNextMemberId } = useLibrary();
  const { showToast } = useToast();
  const navigate = useNavigate();

  const existingEmails = members.map((m) => m.email);
  const nextId = getNextMemberId();

  const handleSubmit = (data: {
    name: string;
    email: string;
    phone: string;
    address: string;
    status: MemberStatus;
  }) => {
    const res = addMember(data);

    if (res.success) {
      showToast('success', 'Anggota berhasil ditambahkan.');
      navigate('/admin/members');
      return { success: true, message: res.message };
    } else {
      showToast('error', res.message);
      return { success: false, message: res.message };
    }
  };

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <Link to="/admin/members">
          <Button variant="ghost" size="sm" icon={<ArrowLeft size={16} />}>
            Kembali
          </Button>
        </Link>
        <div>
          <h2 className="text-xl font-bold text-slate-900 tracking-tight">Tambah Anggota Baru</h2>
          <p className="text-xs text-slate-500">
            Daftarkan anggota perpustakaan baru untuk mendapatkan hak akses peminjaman buku.
          </p>
        </div>
      </div>

      {/* Reusable MemberForm */}
      <MemberForm
        isEdit={false}
        autoGeneratedId={nextId}
        existingEmails={existingEmails}
        onSubmit={handleSubmit}
        onCancel={() => navigate('/admin/members')}
      />
    </div>
  );
};

